name: Build

on:
  pull_request:
    branch:
      - main

jobs:
  set-up:
    name: Set-Up
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature') || startsWith(github.head_ref, 'fix') || startsWith(github.head_ref, 'dependabot') || startsWith(github.head_ref, 'test') }}
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install dependencies
        run: go mod tidy
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - set-up
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Linting
        run: go fmt ./...
